# Generated by Django 5.0.4 on 2024-07-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_charge_vente_remboursement_venteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venteitem',
            name='prix_unitaire',
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venteitem',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
