# Generated by Django 5.0.4 on 2024-07-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacite', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='batiment_photos/')),
            ],
        ),
    ]
